Bk matplotlib
CertifaiAI/basics-of-data-analytics pull request #5
Opened 2021-04-15 08:11 UTC by evanyeohboonkhai

2021-04-28 00:46 UTC, evanyeohboonkhai commented
Please have a view @KianYang-Lee  @scot-certifai

2021-05-02 00:43 UTC, KianYang-Lee reviewed
Code-wise is executable and content has managed to cover basics of Matplotlib. Also included some suggestions for formatting to @evanyeohboonkhai  Can you kindly take a look too @scot-certifai ? would appreciate that.

2021-05-02 00:43 UTC, KianYang-Lee commented on Matplotlib/Solution/03 - Creating different types of graphs with Pyplot.ipynb
> +    "# 02 - Creating different types of graphs with Pyplot\n",
Heading index different with notebook title, please correct

2021-05-02 00:43 UTC, KianYang-Lee commented on Matplotlib/Solution/04 - Creating different types of graphs with Pyplot (Exercise).ipynb
> +    "## <a name=\"Exercise \">Exercise</a>\n",
As per what discussed, please include notebook name as the heading for tilte

2021-05-02 00:43 UTC, KianYang-Lee commented on Matplotlib/Solution/02 - Getting started with Pyplot (Exercise).ipynb
> +    "## <a name=\"Exercise\">Exercise</a>\n",
As per what discussed, please include notebook name as the heading for tilte

2021-05-03 03:13 UTC, evanyeohboonkhai commented
Thanks, @KianYang-Lee  for notice the title, I made a modification to that. Please have a view.

2021-05-03 05:50 UTC, KianYang-Lee commented
Took a view, good to go.

2021-05-03 06:25 UTC, evanyeohboonkhai commented
@scot-certifai  if good from your side please merged it. Thanks

2021-05-03 07:06 UTC, scot-certifai requested changes
Hi @evanyeohboonkhai . I've reviewed the code and they all seem to work fine and I didn't catch any issue with the formats. As for the grammar, I'd like to suggest you to install the Grammarly extension for Microsoft word. You may also follow the guide [here](https://towardsdatascience.com/7-essential-tips-for-writing-with-jupyter-notebook-60972a1a8901) to convert jupyter notebook to .docx. Based on the suggested corrections provided by the Grammarly extension in word, you may edit your notebook accordingly. This is the only way that we can proof read our notebooks until Grammarly supports Jupyter Notebooks.

2021-05-04 08:21 UTC, evanyeohboonkhai commented
@scot-certifai  All the markdown is send to Grammarly and modification is done. Please have a view at it. Thanks.

2021-05-05 09:06 UTC, scot-certifai requested changes

2021-05-05 09:06 UTC, scot-certifai commented on Matplotlib/solution/01 - Getting started with Pyplot.ipynb
> +{
I believe this 'solution' folder is mistakenly created. Can you please remove this folder @evanyeohboonkhai ? I will make the merge soon after. The rest looks good to me.

2021-05-05 09:19 UTC, merged